// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pzoodkjepcarxnawuxoa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVzeG1vYXhqbHZ2eXB4b2NndWRkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjM0MTUwNTQsImV4cCI6MjA3ODk5MTA1NH0.BCl1t9QJMA1Feb-r27XOKKD1434hNYJAq6x3_4qV13s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});